spring: 
 datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.196.210.239:3306/microservice_mallmanagement
    username: user01
    password: 1@3$Qwer
  cloud: 
    inetutils:
      preferredNetworks: 
        - 10.0

eureka:
  instance:
    prefer-ip-address: true